version: '3.9'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: eventlook
      POSTGRES_PASSWORD: eventlook
      POSTGRES_DB: eventlook
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U eventlook' ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'

  backend:
    build:
      context: ./backend
    environment:
      PORT: 3000
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: eventlook
      DATABASE_PASSWORD: eventlook
      DATABASE_NAME: eventlook
      TYPEORM_LOGGING: 'true'
      FRONTEND_URL: http://localhost:8080
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3000:3000'

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - '8080:80'

volumes:
  db_data:

